### ISSUE TITLE
Can it be used for decode h264 video?

### ISSUE THREAD

**Issue by evaniswong** [numbqq/codec_s905x#1]
老哥可以介绍一下这个是有什么作用吗？ 我有个N1盒子，想在桌面硬解视频。
我试过编译了5.2内核把LIMA DRIVER选上了还是没用，桌面也视乎没有GPU加速的效果。

**Comment by numbqq** [comment]
这个codec库只适用于Amlogic linux 3.14 和 4.9内核。

主线是不用这个库的，主线用的是标准的V4L2 m2m。但是主线现在视频解码支持还不是很完善，只能硬解部分格式。

**Comment by evaniswong** [comment]
能得到大神回复简直受宠若惊，哈哈，谢提示，我再研究研究
